### ISSUE TITLE
Boundary between IPF and Husky

### ISSUE THREAD

**Issue by qligier** [project-husky/husky#15]
Hi all,

We should decide where to put the boundary between IPF and Husky, particularly for national transaction implementations. Some are in IPF (CH:PPQ, CH:CPI, ...) and a few are in Husky (CH:PHARM-1 and CH:PHARM-5). Not sure if other parts of the code are concerned by that.

I've no strong feeling on this one.
The only thing is that, if we want to move the last two to IPF, we should do it before they make it to a release here, it would be a dumb breaking change.

**Comment by project-husky-owner** [comment]
Refactoring the communication to have  clean stuff also in convenience interfaces.
Bigger issue -> Step 2 of Migration (eHS/IHE; financial points)

**Comment by project-husky-owner** [comment]
@qligier ist this solved with the new API Service?
