### ISSUE TITLE
CH EMED EPR: missing getters/setters for performer and wasSubstituted on MedicationDispense

### ISSUE THREAD

**Issue by qligier** [project-husky/husky#154]
On `ChEmedEprMedicationDispense`, there are no convenience setters or getters for the performer and wasSubstituted (see [CHEMEDEPRMedicationDispense](https://fhir.ch/ig/ch-emed-epr/StructureDefinition-ch-emed-epr-medicationdispense.html)).

**Comment by dvribeira** [comment]
resolveMedicalAuthor as implementation of the ChEmedEprEntry returns the performer, that keeps it coherent with the rest of the resources (to use the same nomenclature), but you can add an extra method ofc

**Comment by qligier** [comment]
Right, thanks! I can make `resolveMedicalAuthor()` return a PractitionerRole, as set in the IG.

**Comment by dvribeira** [comment]
Ah I see, that's what you wanted, then you will need another method, otherwise it will break the implementation of the ChEmedEprEntry interface.

**Comment by qligier** [comment]
Ah, I forgot it comes from an interface. Then yes, I guess having two methods (`Author resolveMedicalAuthor()` and `ChEmedEprPractitionerRole resolvePerformer()`) will be a good solution.
