### ISSUE TITLE
CH-EMED-EPR: support language in setters with enums

### ISSUE THREAD

**Issue by qligier** [project-husky/husky#177]
When a setter is taking an enum as input (such as `ChEmedEprMedication.setForm(PharmaceuticalDoseFormEdqm)`), an equivalent method that takes a language should be implemented (`ChEmedEprMedication.setForm(PharmaceuticalDoseFormEdqm, LanguageCode)`).
This is needed to set the display name in the same language as the containing document, because that is checked by the FHIR validator (otherwise a warning or error is thrown).

Blocked by #176.

**Comment by dvribeira** [comment]
@qligier I think this was done with https://github.com/project-husky/husky/pull/196 and can be closed or is there anything else to be done?

**Comment by qligier** [comment]
Indeed, thanks! I forgot to reference that issue.

Fixed with fc0544d45b7eadaee8aad3f13739d7c1b8f4c909
