### ISSUE TITLE
Any plans for updating the Spring dependencies?

### ISSUE THREAD

**Issue by jkiddo** [project-husky/husky#180]
Are there any plans to update the Spring Boot (and friends) to 3.X?

https://github.com/project-husky/husky/blob/f839e4dfed3c88d204912bd8a76b0ac787bfb01f/pom.xml#L40

**Comment by ralych** [comment]
@jkiddo see [#60](https://github.com/project-husky/husky/issues/60)
we are still waiting on the release of IPF to update all libs...
