### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by msmock** [project-husky/husky#31]
When installing using the installation guide I end up with a lot of errors in eclipse of type 

"The package javax.xml.parsers is accessible from more than one module: <unnamed>, java.xml" 

which seems to be related to recursive dependencies declared in the project.

**Comment by project-husky-owner** [comment]
@qligier do you have a solution for this problem?

**Comment by qligier** [comment]
No idea, there's no `module-info.java` file in the project. It seems to be a misconfiguration.

**Comment by project-husky-owner** [comment]
is fice with https://github.com/project-husky/husky/commit/c51557ecbca27672f4ae995f8beabb77b9eb46cc
