### ISSUE TITLE
Build Probleme mit language level

### ISSUE THREAD

**Issue by msmock** [project-husky/husky#32]
Ich habe immer wieder Build Probleme mit den Klassen in Husky, in denen in instanceof checks Objekte deklariert werden, z.B. 

if (!(o instanceof final **IheXon that**)) ...

Um trotzdem Tests ausführen zu können muss ich z.B. in IntelliJ "experimentielle Java Features" zulassen. Bei jedem Reload des Maven Projects wird das aber wieder überschrieben. 

Wenn es kein Problem von IntelliJ allein ist, dann sollten wir das Problem in Husky lösen (Maven Configuration?) oder auf das Feature (object declaration in if clauses) verzichten.

**Comment by msmock** [comment]
giving up. Cant get it running with IntelliJ either.

**Comment by ralych** [comment]
Please add reference to the class/line in the code where the problematic definitons are defined.

**Comment by msmock** [comment]
Solved with updating to latest IntelliJ
