### ISSUE TITLE
separation of unit and integration tests

### ISSUE THREAD

**Issue by msmock** [project-husky/husky#34]
The project to port the eHealth Connector to Husky was the first step of all the actions planned for Husky. 

The second action pack was to collect all integration tests (against gazelle) to a separate projects to be able to run and extend them without touching and re-building the core code. 

This is a high priority task to be organized as soon as possible.

**Comment by qligier** [comment]
We can set up the CI in the new project to run daily/weekly, download the master version of Husky and use it to run the integration tests.

**Comment by project-husky-owner** [comment]
Yes Integration tests should be in a separate project for integration tests and not in the "code" project

**Comment by project-husky-owner** [comment]
Intergration test project is here https://github.com/project-husky/husky-integration-tests

Migration is not yet finished

**Comment by project-husky-owner** [comment]
done by release 2.0.0
