### ISSUE TITLE
java.lang.IllegalArgumentException: Unsupported class file major version 62

### ISSUE THREAD

**Issue by msmock** [project-husky/husky#35]
Many unit tests produce an exception "java.lang.IllegalArgumentException: Unsupported class file major version 62". Seems that some libraries are compiled with java 18, while we require Java 17.

**Comment by qligier** [comment]
This seems to be a misconfiguration on your side, maybe in your IDE? Everything is tested with Java 17; I work with that version and so is configured the CI.

**Comment by project-husky-owner** [comment]
just build the whole project without exceptions.
