### ISSUE TITLE
PIX Api needs refactoring

### ISSUE THREAD

**Issue by msmock** [project-husky/husky#39]
The PIX API is quite cumbersome. It's not implemented in an intuitive way and currently requires a trial and error approach to get it up and running. The class hierarchy is no longer helpful and some method parameter are obsolet, or must be set multiple times.  

The future project for refactoring the husky convenience API shall cover the current PIX and PDQ implementation.  A general request builder pattern which applies to all IHE ITI transactions should be used in husky.

**Comment by qligier** [comment]
I've added the convenient `PixV3QueryRequest` and `PixV3QueryResponse` classes to IPF, so PIX should be quite easy to use.

For PDQ, `V3PdqConsumerQuery` and `V3PdqConsumerResponse` are harder to use. Simplified models could be made for specific use cases.

**Comment by project-husky-owner** [comment]
@msmock @qligier does the new API Service solve it? if yes, please close issue.

**Comment by msmock** [comment]
Fixed with service api.
