### ISSUE TITLE
Convert a Code to II or CX String?

### ISSUE THREAD

**Issue by msmock** [project-husky/husky#44]
In the vaccination module we need to convert CX codes for EPR SPID and CII codes for authorRoles to the String representation ( "HCP^^^&2.16.756.5.30.1.127.3.10.6&ISO"). 

I can't find helper methods to do the conversion. 

Any help is appreciated.

**Comment by qligier** [comment]
Hi Martin,

There's a utility class at `org.husky.common.utils.datatypes.IheCx`. Usually, I use IPF's `org.openehealth.ipf.commons.ihe.xds.core.metadata.Identifiable` class to deal with CX:
```java
final var identifiable = Hl7v2Based.parse(string, Identifiable.class);
final var string = Hl7v2Based.render(identifiable);
```

Not sure what a CII is. Did you mean II?

**Comment by msmock** [comment]
Yes. Sorry, meant II for role codes.

**Comment by qligier** [comment]
What's the issue with IIs? The object should be pretty simple to work with

**Comment by ralych** [comment]
@msmock @qligier what is the status of the issue here? ist there a solution?

**Comment by qligier** [comment]
For CX, IPF's Identifiable is useful. II should be quite easy to use by itself, so unless @msmock still has questions, I guess this issue can be closed.

**Comment by project-husky-owner** [comment]
seems to be solve. no feedback to questions...
