### ISSUE TITLE
Branch cleaning

### ISSUE THREAD

**Issue by qligier** [project-husky/husky#49]
There are a few branches that have been merged back to master but still exists. These should be deleted, except if they're being reused.

1. [DM-Playground-Tests](https://github.com/project-husky/husky/tree/DM-Playground-Tests)
2. [Playground-Tests](https://github.com/project-husky/husky/tree/Playground-Tests)
3. [CH-PixV3](https://github.com/project-husky/husky/tree/CH-PixV3)
4. [CH-RegistryStoredQueryTest](https://github.com/project-husky/husky/tree/CH-RegistryStoredQueryTest)
5. [CH-Provide-and-Register-with-XUA-](https://github.com/project-husky/husky/tree/CH-Provide-and-Register-with-XUA-)
6. ~feat/austrian_extensions~

@ajungwirth, @msmock Is it ok to delete these?

**Comment by ajungwirth** [comment]
I have deleted my branch [feat/austrian_extensions](https://github.com/project-husky/husky/tree/feat/austrian_extensions)

**Comment by project-husky-owner** [comment]
@msmock @qligier what is the status here?
there are still branches not deleted?

**Comment by qligier** [comment]
The first five branches still exist and should probably be deleted, since they've been merged. @msmock ?
