### ISSUE TITLE
ChEmedEprValidatorTest.validateDocumentBundle failing

### ISSUE THREAD

**Issue by project-husky-owner** [project-husky/husky#84]
06:01:39.667 [main] INFO org.projecthusky.fhir.emed.ch.epr.validator.ChEmedEprValidatorTest - [INFORMATION][UNKNOWN] Code System URI 'urn:oid:2.51.1.1' is unknown so the code cannot be validated
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 20.861 s <<< FAILURE! - in org.projecthusky.fhir.emed.ch.epr.validator.ChEmedEprValidatorTest
[ERROR] org.projecthusky.fhir.emed.ch.epr.validator.ChEmedEprValidatorTest.validateDocumentBundle  Time elapsed: 20.788 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>

**Comment by dvribeira** [comment]
The XML resource files are not up to date. The current XML files from the CH-EMED examples should be used.
