### ISSUE TITLE
CH-EMED-EPR: HtmlNarrativeGenerator add check to include or not a statement on the PDF

### ISSUE THREAD

**Issue by dvribeira** [project-husky/husky#91]
With the possibility of requesting PMLC documents with non-active treatments, the generator might receive a list of medication statements for active and non-active treatments. The generator should ignore non-active medication statements.

**Comment by qligier** [comment]
Wouldn't it be weird to allow requesting non-active treatments for a PDF, but omit them in the actual document? I would either refuse that particular request in the PMP, or include them in the PDF.

**Comment by dvribeira** [comment]
Since the behaviour described by the issue was implemented and merged almost a year ago, I think it is sound to close this ticket. Should the implemented behaviour be reviewed it is better to create a new issue.
